news/urls.py
from django.urls import path

from .views import (
    PostList,
    PostDetail,
    PostCreateView,
    PostDeleteView,
    PostUpdateView,
    PostSearch,
    i_am_author,
    CategoryDetailView,
    subscribe,
    unsubscribe,
)

urlpatterns = [
    path("", PostList.as_view(), name="list"),
    path("search/", PostSearch.as_view(), name="search"),
    path("<int:pk>", PostDetail.as_view(), name="post"),
    path("create", PostCreateView.as_view(), name="create"),
    path("<int:pk>/edit", PostUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete", PostDeleteView.as_view(), name="delete"),
    path("be_author/", i_am_author, name="be_author"),
    path("category/<int:pk>", CategoryDetailView.as_view(), name="category"),
    path("category/<int:pk>/subscribe", subscribe, name="subscribe"),
    path("category/<int:pk>/unsubscribe", unsubscribe, name="unsubscribe"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account import views as allauth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("posts/", include(("news.urls", "news"), namespace="news")),
    path("accounts/", include("allauth.urls")),
    path("accounts/logout/", allauth_views.LogoutView.as_view(), name="logout"),
    path("accounts/login/", allauth_views.LoginView.as_view(), name="login"),
    path("accounts/signup/", allauth_views.SignupView.as_view(), name="signup"),
]

news/models.py
from datetime import datetime, timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAutor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postrating=Sum("rating"))
        pRat = 0
        pRat += postRat.get("postRating")

        commentRat = self.authorUser.comment_set.all().aggregate(
            postrating=Sum("rating")
        )
        cRat = 0
        cRat += commentRat.get("commentRating")

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscriber = models.ManyToManyField(User, through="CategorySubscribers")


class CategorySubscribers(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subscriber = models.ForeignKey(User, on_delete=models.CASCADE)


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = "NW"
    ARTICLE = "AR"
    POST_TYPE = (
        (NEWS, "Новость"),
        (ARTICLE, "Статья"),
    )
    type = models.CharField(max_length=2, choices=POST_TYPE, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + "..."

    def __str__(self):
        return f"{self.title.title()}: {self.text[:50]}  {self.dateCreation} "

    def get_absolute_url(self):
        return f"/posts/{self.id}"


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comment_post"
    )
    commentUser = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comment_user"
    )
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.commentUser.username

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


models.FloatField(default=0.0)

news/forms.py
from django.forms import ModelForm
from .models import Post
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class NewsForm(ModelForm):
    class Meta:
        model = Post
        fields = ["author", "text", "title", "type", "category"]


class BasicSignupForm(SignupForm):
    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get_or_create(name="common")[0]
        basic_group.user_set.add(user)
        return user

news/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .filters import NewsFilter
from .forms import NewsForm
from .models import Post, Category
from django.core.paginator import Paginator

import logging

logger = logging.getLogger("django")


class PostList(ListView):
    model = Post
    template_name = "postlist.html"
    context_object_name = "posts"
    ordering = ["-dateCreation"]
    paginate_by = 4
    form_class = NewsForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = NewsFilter(self.request.GET, queryset=self.get_queryset())

        context["form"] = self.form_class()
        context["is_not_authors"] = not self.request.user.groups.filter(
            name="authors"
        ).exists()
        return context

    def post(self, request, *args, **kwargs):
        form = self.NewsForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("news")
        else:
            context = self.get_context_data(**kwargs)
            context["form"] = form
            return self.render_to_response(context)


@login_required
def i_am_author(request):
    user = request.user
    authors_group = Group.objects.get(name="authors")
    if not request.user.groups.filter(name="authors").exists():
        authors_group.user_set.add(user)
    return redirect("/posts")


class PostDetail(DetailView):
    model = Post
    template_name = "post.html"
    context_object_name = "post"


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = "news.add_post"
    template_name = "create.html"
    form_class = NewsForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        self.object = form.save()

        post_categories = self.object.category.all()

        for category in post_categories:
            for subscriber in category.subscriber.all():
                html_content = render_to_string(
                    "send_mail_subscribe_to_news.html",
                    {
                        "user": subscriber,
                        "post": self.object,
                    },
                )

                msg = EmailMultiAlternatives(
                    subject=f"{self.object.title}",
                    body=self.object.text,
                    from_email="dariastore@yandex.ru",
                    to=[f"{subscriber.email}"],
                )
                msg.attach_alternative(html_content, "text/html")
                msg.send()

        return HttpResponseRedirect(self.get_success_url())


class PostDetailView(DetailView):
    model = Post
    template_name = "post.html"
    context_object_name = "post"
    queryset = Post.objects.all()


class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = "news.update_post"
    template_name = "create.html"
    form_class = NewsForm

    def get_object(self, **kwargs):
        id = self.kwargs.get("pk")
        return Post.objects.get(pk=id)


class PostDeleteView(DeleteView):
    template_name = "delete.html"
    queryset = Post.objects.all()
    success_url = reverse_lazy("news:list")


class PostSearch(ListView):
    model = Post
    template_name = "search.html"
    context_object_name = "search"
    ordering = ["-dateCreation"]
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = NewsFilter(self.request.GET, queryset=self.get_queryset())
        return context


class CategoryDetailView(DetailView):
    model = Category
    template_name = "category.html"
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(id=self.kwargs["pk"])
        context["subscribers"] = category.subscriber.all()
        return context


@login_required
def subscribe(request, pk):
    category = Category.objects.get(pk=pk)
    category.subscriber.add(request.user.id)
    return HttpResponseRedirect(reverse("news:category", args=[pk]))


@login_required
def unsubscribe(request, pk):
    category = Category.objects.get(pk=pk)
    category.subscriber.remove(request.user.id)
    return HttpResponseRedirect(reverse("news:category", args=[pk]))

news/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {{category.name}}

    {% if user not in subscribers %}
        <form action="{% url 'news:subscribe' category.pk %}" method="Post">
            {% csrf_token %}
            <input type="submit" value="Подписаться"/>
        </form>
    {% else %}
        <form action="{% url 'news:unsubscribe' category.pk %}" method="Post">
            {% csrf_token %}
            <input type="submit" value="Отписаться"/>
        </form>
    {% endif %}
</head>
<body>

</body>
</html>

news/templates/create.html
{% extends 'flatpages/default.html' %}
{% block title %} News list {% endblock title %}
{% block content %}
<h3>Создаем новостной блок</h3>
<form method="POST">
    {% csrf_token %} 
    {{ form }}
    <input type="submit" value="Добавить новость">
</form>
{% endblock content %}

news/templates/delete.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %} News list {% endblock title %}
{% block content %}
<h2>Вы действительно хотите удалить данную новость?</h2>
   <table>
        <tr>
            <td>
                <b> {{ post.name|censor }} </b>

                <i>{{ post.dateCreation|date:'m-d-Y g:i'  }}</i>
            </td>
        </tr>
        <tr>
            <td>

                {{ post.text|censor }}
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <i>{{ post.postCategory }}</i>  |

                    <b>{{ post.author }}</b>
                </p>
            </td>

        </tr>
    </table>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
{% endblock content %}

news/templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}.
{% block title %}
Post
{% endblock title %}
{% block content %}
<h1>{{ post.title }}</h1>
<h2>{% for category in post.category.all %}
    <a href="{% url 'news:category' category.id %}">{{ category.name }}</a>
  {% endfor %}</h2>
<i>{{ post.dateCreation|date:'m-d-Y g:i'  }}</i>
<div>{{ post.text }}</div>
<a href="{% url 'news:edit' post.id %}">
    Редактировать пост
      </a>
<a href="{% url 'news:delete' post.id %}">
           Удалить пост
       </a>
{% endblock content %}

news/templates/postlist.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}.
{% block title %}
<h1>Все посты</h1>
{% endblock title %}
{% block content %}
<h2>Здравствуйте {{request.user.username}}!</h2>
<h3>Количество новостей: {{ posts|length }}</h3>
<tr>
    <td>
        Заголовок
    </td>
    <td>
        Категория
    </td>
    <td>
        Дата публикации
    </td>
    <td>
        Превью статьи
    </td>
</tr>
{% for post in posts %}
<tr>
    <td>
        <a href="{% url 'news:post' post.id %}">{{ post.title }}</a>
    </td>
    <td>
        {% for category in post.postCategory.all %}
        <a href="{% url 'news:category' category.id %}">{{category}}</a>
        {% endfor %}
    </td>
    <td>
        {{ post.dateCreation|date:'M-d-Y H:m'}}
    </td>
    <td>
        {{ post.text|truncatechars:50|censor }}
    </td>
</tr>
{% endfor %}
<br><br>
<a class="btn btn-primary" href="{% url 'news:create' %}">
    Создать пост
</a>
<br><br>
<a class="btn btn-primary" href="{% url 'login' %}">
    Войти в аккаунт
</a>
<br><br>
<a class="btn btn-primary" href="{% url 'logout' %}">
    Выйти из аккаунта
</a>
<br><br>
<a class="btn btn-primary" href="{% url 'signup' %}">
    Регистрация
</a>
<br><br>
{% if is_not_authors %}
<button><a class="btn btn-primary" href="{% url 'news:be_author' %}">Стать автором</a></button>
{% else %}
<h3>Вы уже являетесь автором</h3>
{% endif %}

{% endblock content %}

news/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
Search
{% endblock title %}
{% block content %}
    <h1>Поиск в новостях</h1>
        <form method="GET">
         {{ filter.form }}
         <input type="submit" value="Найти">
        </form>
        <table>
            {% for posts in filter.qs %}
            <tr>
            <td>
                {{ post.name|censor }}
            </td>
            <td>
                {{ post.author }}
            </td>
            <td>
               {{ post.dateCreation|date:'m d Y' }}
            </td>
            <td>
               {{ post.text|censor|truncatechars:50 }}
            </td>
             <td>
               {{ post.categoryType }}
            </td>
            </tr>
        {% endfor %}
        </table>

      {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a href="?page=1">В начало!</a>
                <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a>{{ num }}</a>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">>>></a>
                <a href="?page={{ page_obj.paginator.num_pages }}">В конец!</a>
            {% endif %}

        {% endif %}
{% endblock content %}

news/templates/send_mail_subscribe_to_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2> Здравствуй, {{ user.username }} Новая статья в твоем любимом разделе!</h2>
    <h3> {{ post.title }}</h3>
    <p>{{ post.text|truncatechars:50 }} </p>
    <p>Чтобы прочитать полную статью, перейдите по ссылке ниже:</p>
    <p><a href="http://127.0.0.1:8090/{{ post.get_absolute_url }}">{{ post.title }}</a></p>
</body>
</html>

news/templates/weekly_article_list_email.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Еженедельный список новых статей</title>
</head>
<body>
        <h2>Здравствуйте, {{ subscriber.username }}!</h2>
        <p>Ниже представлен список новых статей по категории {{ category.name }} за последнюю неделю:</p>
        <ul>
            {% for post in post_list %}
                <li><a href="http://127.0.0.1:8090/{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
</body>
</html>